# Generated by Django 5.2 on 2026-04-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_user_salary_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('blocked', 'Blocked')], default='inactive', max_length=10),
        ),
    ]
