# Generated by Django 5.2 on 2026-04-24 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_bankcard_balance_alter_bankcard_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcard',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='card_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
