# Generated by Django 5.2 on 2026-04-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_remove_bankcard_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='expiry_date',
            field=models.CharField(max_length=5),
        ),
    ]
