# Generated by Django 5.2 on 2026-04-24 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_bankcard_expiry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankcard',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bank kartasi', 'verbose_name_plural': 'Bank kartalari'},
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Balans'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='card_number',
            field=models.CharField(help_text='16 xonali raqam', max_length=16, unique=True, verbose_name='Karta raqami'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='expiry_date',
            field=models.CharField(help_text='Format: MM/YY (masalan: 12/26)', max_length=5, verbose_name='Amal qilish muddati'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='phone',
            field=models.CharField(max_length=16, verbose_name="Bog'langan telefon"),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('expired', "Muddati o'tgan"), ('blocked', 'Bloklangan')], default='inactive', max_length=10, verbose_name='Holati'),
        ),
    ]
