# Generated by Django 5.2 on 2026-04-27 05:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_bankcard_options_alter_bankcard_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
